a=int(input("enter the value of a"))
b=int(input("enter the value of b"))
print("add val ",a+b)
a=int(input("enter the value of a"))
b=int(input("enter the value of b"))
print("add val ",a-b)
a=int(input("enter the value of a"))
b=int(input("enter the value of b"))
print("add val ",a*b)
a=int(input("enter the value of a"))
b=int(input("enter the value of b"))
print("add val ",a/b)
a=int(input("enter the value of a"))
b=int(input("enter the value of b"))
print("add val ",a//b)
a=int(input("enter the value of a"))
b=int(input("enter the value of b"))
print("add val ",a%b)
a=int(input("enter the value of a"))
b=int(input("enter the value of b"))
print("add val ",a**b)
